api:
  port: 8001
  metrics_port: 9001
  metrics_name: api
  mail_hub_ctx: hub
  mail_tpl_dir: ./internal/api/http/templates/
  host: http://localhost:8001
  mail_preview_max_len: 60

project:
  project_base_dir: 2023_1_Seekers
logger:
  logs_dir: logs/app/
  logs_api_file_name: api/dev_
  logs_auth_file_name: auth/dev_
  logs_file_service_file_name: file_service/dev_
  logs_user_file_name: user/dev_
  logs_mail_file_name: mail/dev_
  logs_use_std_out: true
  logs_time_format: 2006-01-02_15:04:05_MST

file_grpc_service:
  port: 8005
  host: 127.0.0.1
  metrics_port: 9003
  metrics_name: file_service

user_grpc_service:
  port: 8006
  host: 127.0.0.1
  metrics_port: 9005
  metrics_name: user

auth_grpc_service:
  port: 8007
  host: 127.0.0.1
  metrics_port: 9002
  metrics_name: auth

mail_grpc_service:
  port: 8008
  host: 127.0.0.1
  metrics_port: 9004
  metrics_name: mail

smtp_server:
  port: 25
  domain: mailbx
  read_timeout: 10s
  write_timeout_timeout: 10s
  max_message_bytes: 1048576
  max_recipients: 50
  allow_insecure_auth: false
  cert_file: /etc/letsencrypt/live/mailbx.ru/fullchain.pem
  key_file: /etc/letsencrypt/live/mailbx.ru/privkey.pem
  dkim_private_key_file: /home/ubuntu/dkim/priv.key

s3:
  s3_region: eu-west-2
  s3_endpoint: https://hb.bizmrg.com
  s3_avatar_bucket: avatars_mailbox_vkcloud
  s3_attach_bucket: attachs_mailbox_vkcloud

sessions:
  cookie_name: MailBxSession
  cookie_ttl: 2400h0m0s
  cookie_path: /
  csrf_header: Csrf-Token
  cookie_len: 32

routes:
  route_prefix: /api/v1

  route_signin: /signin
  route_signup: /signup
  route_logout: /logout
  route_auth: /auth
  route_csrf: /csrf

  route_message: /message/{id:[0-9]+}
  route_attach: /attach/{id:[0-9]+}
  route_message_attaches: /message/{id:[0-9]+}/attaches
  route_preview_attach: /attach/{id:[0-9]+}/preview
  route_external_attach: /external/attach/{id:[0-9]+}
  route_send_message: /message/send
  route_save_draft_message: /message/save
  route_read_message: /message/{id:[0-9]+}/read
  route_unread_message: /message/{id:[0-9]+}/unread
  route_move_to_folder: /message/{id:[0-9]+}/move
  route_move_to_folder_query_folder_slug: folderSlug
  route_get_folders: /folders
  route_folder: /folder/{slug}
  route_search: /messages/search
  route_recipients: /recipients/search
  route_create_folder: /folder/create
  route_edit_folder: /folder/{slug}/edit
  route_get_folders_is_custom: custom
  query_access_key: accessKey

  route_user: /user
  route_user_info: /user/info
  route_user_avatar: /user/avatar
  route_pw: /user/pw
  route_user_avatar_query_email: email
  route_user_info_query_email: email

user_service:
  max_image_size: 2147483648
  user_form_new_avatar: avatar
  user_default_avatar_size: 46
  default_avatar: default_avatar.png
  avatar_ttf_path: ./cmd/config/wqy-zenhei.ttf

password:
  password_min_len: 5
  password_salt_len: 10

mail:
  post_domain: "mailbx.ru"
  post_at_domain: "@mailbx.ru"

cors:
  allowed_headers:
    - Content-Type
    - Content-Length
    - X-Csrf-Token
    - application/json
    - text/xml
  allowed_origins:
    - http://127.0.0.1:8002
    - http://localhost:8002
    - http://localhost
    - http://127.0.0.1
    - http://89.208.197.150:8002
    - https://mailbx.ru
    - https://www.mailbx.ru
  allowed_methods:
    - POST
    - GET
    - PUT,
    - DELETE
