version: "3.8"

services:
  app:
    depends_on:
      - minio
      - create-bucket
    build: ./
    network_mode: "host"
    environment:
      - ...

  minio:
    image: minio/minio:RELEASE.2021-01-05T05-22-38Z
    networks:
      - minio-net
    volumes:
      - ./minio_data:/export
    command: server /export
    environment:
      MINIO_ACCESS_KEY: ACCESS_TO_ENV!
      MINIO_SECRET_KEY: SECRET_TO_ENV!
    ports:
      - "9000:9000"

  create-bucket:
    image: minio/mc:RELEASE.2021-01-05T05-03-58Z
    networks:
      - minio-net
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add minioClient http://minio:9000 ACCESS_TO_ENV! SECRET_TO_ENV!;
      /usr/bin/mc mb minioClient/avatars; 
      exit 0;
      "

networks:
  minio-net:
    driver: bridge
    name: minio-net
    external: false
