version: "3.8"

services:
  app:
    depends_on:
      db:
        condition: service_healthy
      create-bucket:
        condition: service_started
      minio:
        condition: service_started
      cache:
        condition: service_started
    volumes:
      - $GOPATH/pkg/mod:/go/pkg/mod
    build: ./
    networks:
      my_network:
        ipv4_address: 172.28.0.2
    #    network_mode: "host"
    ports:
      - "8001:8001"
    environment:
      REDIS_HOST: "172.28.0.7"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "no_env_pw"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "no_env_pw"
      POSTGRES_HOST: "172.28.0.3"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "postgres"
      POSTGRES_SCHEMA: "mail"
      S3_SECRET_KEY: "no_env_secret_key"
      S3_ACCESS_KEY: "no_env_access_key"
  db:
    image: postgres:latest
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "no_env_pw"
      POSTGRES_DB: "postgres"
    networks:
      my_network:
        ipv4_address: 172.28.0.3
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
    #    restart: always
    volumes:
      # - TODO DATA
      - ./scripts/sql:/docker-entrypoint-initdb.d
      - ./logs/postgres:/logs

  admin_db:
    networks:
      my_network:
        ipv4_address: 172.28.0.4
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "True"
    ports:
      - "5050:80"
    depends_on:
      - db

  minio:
    image: minio/minio:RELEASE.2021-01-05T05-22-38Z
    networks:
      my_network:
        ipv4_address: 172.28.0.5
    volumes:
      - ./minio_data:/export
    command: server /export
    environment:
      MINIO_SECRET_KEY: "no_env_secret_key"
      MINIO_ACCESS_KEY: "no_env_access_key"
    ports:
      - "9000:9000"

  create-bucket:
    image: minio/mc:RELEASE.2021-01-05T05-03-58Z
    networks:
      my_network:
        ipv4_address: 172.28.0.6
    depends_on:
      - minio
    environment:
      MINIO_SECRET_KEY: "no_env_secret_key"
      MINIO_ACCESS_KEY: "no_env_access_key"
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc config host add minioClient http://172.28.0.5:9000 "no_env_access_key" "no_env_secret_key";
      /usr/bin/mc mb minioClient/avatars_mailbox_vkcloud; 
      sleep 3;
      exit 0;
      "

  cache:
    image: redis:6.2-alpine
    #    restart: always
    ports:
      - '6379:6379'
    networks:
      my_network:
        ipv4_address: 172.28.0.7
    environment:
      REDIS_PASSWORD: "no_env_pw"
    command: redis-server --requirepass "no_env_pw"
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1