// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2023_1_Seekers/internal/auth (interfaces: SessionRepoI)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2023_1_Seekers/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockSessionRepoI is a mock of SessionRepoI interface.
type MockSessionRepoI struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepoIMockRecorder
}

// MockSessionRepoIMockRecorder is the mock recorder for MockSessionRepoI.
type MockSessionRepoIMockRecorder struct {
	mock *MockSessionRepoI
}

// NewMockSessionRepoI creates a new mock instance.
func NewMockSessionRepoI(ctrl *gomock.Controller) *MockSessionRepoI {
	mock := &MockSessionRepoI{ctrl: ctrl}
	mock.recorder = &MockSessionRepoIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepoI) EXPECT() *MockSessionRepoIMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionRepoI) CreateSession(arg0 uint64) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionRepoIMockRecorder) CreateSession(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionRepoI)(nil).CreateSession), arg0)
}

// DeleteSession mocks base method.
func (m *MockSessionRepoI) DeleteSession(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionRepoIMockRecorder) DeleteSession(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionRepoI)(nil).DeleteSession), arg0)
}

// GetSession mocks base method.
func (m *MockSessionRepoI) GetSession(arg0 string) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionRepoIMockRecorder) GetSession(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionRepoI)(nil).GetSession), arg0)
}
