global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: api
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'api:9001' ]

  - job_name: auth
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'auth:9002' ]

  - job_name: file_storage
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'file_storage:9003' ]

  - job_name: mail
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'mail:9004' ]

  - job_name: user
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'user:9005' ]


  - job_name: node
    scrape_interval: 10s
    static_configs:
      - targets: [ 'node:9100' ]
