// Code generated by MockGen. DO NOT EDIT.
// Source: ./session.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2023_1_Seekers/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepoI is a mock of RepoI interface.
type MockRepoI struct {
	ctrl     *gomock.Controller
	recorder *MockRepoIMockRecorder
}

// MockRepoIMockRecorder is the mock recorder for MockRepoI.
type MockRepoIMockRecorder struct {
	mock *MockRepoI
}

// NewMockRepoI creates a new mock instance.
func NewMockRepoI(ctrl *gomock.Controller) *MockRepoI {
	mock := &MockRepoI{ctrl: ctrl}
	mock.recorder = &MockRepoIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoI) EXPECT() *MockRepoIMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockRepoI) CreateSession(uID uint64) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", uID)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockRepoIMockRecorder) CreateSession(uID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockRepoI)(nil).CreateSession), uID)
}

// DeleteSession mocks base method.
func (m *MockRepoI) DeleteSession(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockRepoIMockRecorder) DeleteSession(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockRepoI)(nil).DeleteSession), sessionID)
}

// GetSession mocks base method.
func (m *MockRepoI) GetSession(sessionID string) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", sessionID)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockRepoIMockRecorder) GetSession(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockRepoI)(nil).GetSession), sessionID)
}
