{
 "title": "App monitoring",
 "description": "monitor hits, error hits, timings for api and microcervices (auth, user, mail ,file_service)",
 "tags": [
  "api",
  "microservices",
  "http",
  "grpc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Counts requests per second in rate interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(api_hits[$__rate_interval])*15",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error Hits",
   "type": "timeseries",
   "description": "Error hits per second in rate_interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(api_errors{job=\"api\"}[$__rate_interval])*15",
     "legendFormat": " {{method}} {{code}} {{path}}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(rate(api_timings_bucket[$__rate_interval])*15) by (code, method, path)",
     "legendFormat": "{{code}} {{method}} {{path}}"
    }
   ]
  },
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Counts RPS in rate interval ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(auth_hits[$__rate_interval])*15",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(auth_errors{job=\"auth\"}[$__rate_interval])*15",
     "legendFormat": "{{code}} {{method}}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "max(rate(auth_timings_bucket[$__rate_interval])*15) by (code, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } }
 ]
}