{
 "title": "App monitoring",
 "description": "monitor hits, error hits, timings for api and microcervices (auth, user, mail ,file_service)",
 "tags": [
  "api",
  "microservices",
  "http",
  "grpc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Counts requests per second in rate interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(api_hits[$__rate_interval])*15",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error Hits",
   "type": "timeseries",
   "description": "Error hits per second in rate_interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(api_errors{job=\"api\"}[$__rate_interval])*15",
     "legendFormat": " {{method}} {{code}} {{path}}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "api_timings_sum", "legendFormat": "{{code}} {{method}} {{path}}" }
   ]
  },
  { "title": "Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Counts RPS in rate interval ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(auth_hits[$__rate_interval])*15",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(auth_errors{job=\"auth\"}[$__rate_interval])*15",
     "legendFormat": "{{code}} {{method}}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "auth_timings_sum", "legendFormat": "{{code}} {{method}}" }
   ]
  },
  { "title": "File Sevice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(file_service_hits[$__rate_interval])*15",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(file_service_errors{job=\"file_service\"}[$__rate_interval])*15",
     "legendFormat": "{{code}} {{method}}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "file_service_timings_sum", "legendFormat": "{{code}} {{method}}" }
   ]
  },
  { "title": "Mail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(mail_hits{job=\"mail\"}[$__rate_interval])*15",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "rate(mail_errors{job=\"mail\"}[$__rate_interval])*15",
     "legendFormat": "{{code}} {{method}}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "mail_timings_sum", "legendFormat": "{{code}} {{method}}" }
   ]
  },
  { "title": "User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(user_hits{job=\"user\"}[$__rate_interval])*15",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "rate(user_errors{job=\"user\"}[$__rate_interval])*15",
     "legendFormat": "{{code}} {{method}}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "user_timings_sum", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } }
 ]
}