{
 "title": "System",
 "description": "System metrics",
 "tags": [ "system" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "fstypes", "label": "File System Types", "query": "ext4|fuseblk" }
  ]
 },
 "panels": [
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "content": "<h1>CPU<h1>" },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius) by (instance)",
     "legendFormat": "CPU Temperature"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (instance) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 3 },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])) by (instance) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "running" },
    { "expr": "node_procs_blocked", "legendFormat": "blocked by I/O" }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "options": { "content": "<h1>Memory<h1>" },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Current"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Max" }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": { "content": "<h1>Disk<h1>" },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"$fstypes\"} - node_filesystem_free_bytes{fstype=~\"$fstypes\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext4|fuseblk\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{fstype=~\"$fstypes\"} / node_filesystem_size_bytes{fstype=~\"$fstypes\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "options": { "content": "<h1>Network<h1>" },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!=\"lo\"}[1m]))",
     "legendFormat": "Upload"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!=\"lo\"}[1m]))",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!=\"lo\"}[1m]))",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!=\"lo\"}[1m]))",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}