basePath: /api/v1
definitions:
  errors.JSONError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  models.AuthResponse:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    required:
    - email
    - firstName
    - lastName
    type: object
  models.EditUserInfoResponse:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.Folder:
    properties:
      folder_id:
        type: integer
      folder_slug:
        type: string
      messages_count:
        type: integer
      messages_unseen:
        type: integer
      name:
        type: string
    type: object
  models.FolderResponse:
    properties:
      folder:
        $ref: '#/definitions/models.Folder'
      messages:
        items:
          $ref: '#/definitions/models.MessageInfo'
        type: array
    type: object
  models.FoldersResponse:
    properties:
      count:
        type: integer
      folders:
        items:
          $ref: '#/definitions/models.Folder'
        type: array
    type: object
  models.FormLogin:
    properties:
      login:
        type: string
      password:
        type: string
      remember:
        type: boolean
    required:
    - login
    - password
    - remember
    type: object
  models.FormSignUp:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      login:
        type: string
      password:
        type: string
      repeatPw:
        type: string
    required:
    - firstName
    - lastName
    - login
    - password
    - repeatPw
    type: object
  models.MessageInfo:
    properties:
      created_at:
        type: string
      deleted:
        type: boolean
      favorite:
        type: boolean
      from_user_id:
        $ref: '#/definitions/models.UserInfo'
      message_id:
        type: integer
      recipients:
        items:
          $ref: '#/definitions/models.UserInfo'
        type: array
      reply_to:
        $ref: '#/definitions/models.MessageInfo'
      seen:
        type: boolean
      text:
        type: string
      title:
        type: string
    type: object
  models.MessageResponse:
    properties:
      message:
        $ref: '#/definitions/models.MessageInfo'
    type: object
  models.UserInfo:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    required:
    - email
    - firstName
    - lastName
    type: object
host: localhost:8001
info:
  contact: {}
  title: MailBox Swagger API
  version: "1.0"
paths:
  /folder/{slug}:
    get:
      consumes:
      - application/json
      description: List of folder messages
      parameters:
      - description: FolderSlug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success get list of folder messages
          schema:
            $ref: '#/definitions/models.FolderResponse'
        "400":
          description: invalid url address
          schema:
            $ref: '#/definitions/errors.JSONError'
        "404":
          description: folder not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: GetFolderMessages
      tags:
      - messages
  /folders/:
    get:
      consumes:
      - application/json
      description: List of outgoing messages
      produces:
      - application/json
      responses:
        "200":
          description: success get list of outgoing messages
          schema:
            $ref: '#/definitions/models.FoldersResponse'
        "400":
          description: failed to get user
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: GetFolders
      tags:
      - messages
  /logout:
    post:
      consumes:
      - application/json
      description: user log out
      produces:
      - application/json
      responses:
        "200":
          description: success logout
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: Logout
      tags:
      - auth
  /message/{id}:
    get:
      consumes:
      - application/json
      description: Message
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success get messages
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: invalid url address
          schema:
            $ref: '#/definitions/errors.JSONError'
        "404":
          description: message not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: GetMessage
      tags:
      - messages
  /message/{id}/read:
    post:
      consumes:
      - application/json
      description: Message
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success read message
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: invalid url address
          schema:
            $ref: '#/definitions/errors.JSONError'
        "404":
          description: message not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: GetMessage
      tags:
      - messages
  /message/{id}/unread:
    post:
      consumes:
      - application/json
      description: Message
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success unread message
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: invalid url address
          schema:
            $ref: '#/definitions/errors.JSONError'
        "404":
          description: message not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: GetMessage
      tags:
      - messages
  /message/send:
    post:
      consumes:
      - application/json
      description: Message
      produces:
      - application/json
      responses:
        "200":
          description: success send message
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: no valid emails
          schema:
            $ref: '#/definitions/errors.JSONError'
        "403":
          description: invalid form
          schema:
            $ref: '#/definitions/errors.JSONError'
        "404":
          description: message not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: GetMessage
      tags:
      - messages
  /signin:
    post:
      consumes:
      - application/json
      description: user sign in
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.FormLogin'
      produces:
      - application/json
      responses:
        "200":
          description: success sign in
          schema:
            $ref: '#/definitions/models.AuthResponse'
        "401":
          description: wrong password
          schema:
            $ref: '#/definitions/errors.JSONError'
        "403":
          description: invalid form
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: SignIn
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: user sign up
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.FormSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: user created
          schema:
            $ref: '#/definitions/models.AuthResponse'
        "401":
          description: invalid login
          schema:
            $ref: '#/definitions/errors.JSONError'
        "403":
          description: password too short
          schema:
            $ref: '#/definitions/errors.JSONError'
        "409":
          description: user already exists
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: SignUp
      tags:
      - auth
  /user:
    delete:
      consumes:
      - application/json
      description: delete user
      produces:
      - application/json
      responses:
        "200":
          description: success delete user
        "400":
          description: failed to get user
          schema:
            $ref: '#/definitions/errors.JSONError'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: Delete
      tags:
      - users
  /user/avatar:
    get:
      consumes:
      - application/json
      description: get user avatar
      parameters:
      - description: email
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success get user avatar
          schema:
            items:
              type: integer
            type: array
        "400":
          description: no bucket
          schema:
            $ref: '#/definitions/errors.JSONError'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: GetAvatar
      tags:
      - users
    post:
      consumes:
      - application/json
      description: edit user avatar
      produces:
      - application/json
      responses:
        "200":
          description: success edit user avatar
        "400":
          description: unsupported content type
          schema:
            $ref: '#/definitions/errors.JSONError'
        "403":
          description: invalid form
          schema:
            $ref: '#/definitions/errors.JSONError'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: EditAvatar
      tags:
      - users
  /user/info:
    get:
      consumes:
      - application/json
      description: get info about user
      parameters:
      - description: email
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success get user info
          schema:
            $ref: '#/definitions/models.UserInfo'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: GetInfo
      tags:
      - users
    post:
      consumes:
      - application/json
      description: edit info about user
      produces:
      - application/json
      responses:
        "200":
          description: success edit user info
          schema:
            $ref: '#/definitions/models.EditUserInfoResponse'
        "400":
          description: failed to get user
          schema:
            $ref: '#/definitions/errors.JSONError'
        "403":
          description: invalid form
          schema:
            $ref: '#/definitions/errors.JSONError'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: EditInfo
      tags:
      - users
  /user/pw:
    post:
      consumes:
      - application/json
      description: edit password about user
      produces:
      - application/json
      responses:
        "200":
          description: success edit user password
        "400":
          description: failed to get user
          schema:
            $ref: '#/definitions/errors.JSONError'
        "403":
          description: invalid form
          schema:
            $ref: '#/definitions/errors.JSONError'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/errors.JSONError'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/errors.JSONError'
      summary: EditPw
      tags:
      - users
swagger: "2.0"
