basePath: /api/v1
definitions:
  models.Folder:
    properties:
      folder_id:
        type: integer
      name:
        type: string
      user_id:
        type: integer
    type: object
  models.FolderResponse:
    properties:
      folder:
        $ref: '#/definitions/models.Folder'
      messages:
        items:
          $ref: '#/definitions/models.IncomingMessage'
        type: array
    type: object
  models.FoldersResponse:
    properties:
      folders:
        items:
          $ref: '#/definitions/models.Folder'
        type: array
    type: object
  models.FormLogin:
    properties:
      login:
        type: string
      password:
        type: string
      remember:
        type: boolean
    required:
    - login
    - password
    - remember
    type: object
  models.FormSignUp:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      login:
        type: string
      password:
        type: string
      repeat_pw:
        description: '?'
        type: string
    required:
    - first_name
    - last_name
    - login
    - password
    - repeat_pw
    type: object
  models.InboxResponse:
    properties:
      messages:
        items:
          $ref: '#/definitions/models.IncomingMessage'
        type: array
    type: object
  models.IncomingMessage:
    properties:
      creating_date:
        type: string
      favorite:
        type: boolean
      from_user:
        type: string
      message_id:
        type: integer
      read:
        type: boolean
      text:
        type: string
      title:
        type: string
    type: object
  models.OutboxResponse:
    properties:
      messages:
        items:
          $ref: '#/definitions/models.OutgoingMessage'
        type: array
    type: object
  models.OutgoingMessage:
    properties:
      creating_date:
        type: string
      favorite:
        type: boolean
      message_id:
        type: integer
      read:
        type: boolean
      text:
        type: string
      title:
        type: string
      to_users:
        items:
          type: string
        type: array
    type: object
  models.SignInResponse:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.SignUpResponse:
    properties:
      email:
        type: string
    required:
    - email
    type: object
host: localhost:8001
info:
  contact: {}
  title: MailBox Swagger API
  version: "1.0"
paths:
  /folder/{id}:
    get:
      consumes:
      - application/json
      description: List of outgoing messages
      parameters:
      - description: FolderID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success get list of outgoing messages
          schema:
            $ref: '#/definitions/models.FolderResponse'
        "400":
          description: failed to get folder messages
          schema: {}
        "401":
          description: failed get session
          schema: {}
        "404":
          description: invalid url address
          schema: {}
      summary: GetFolderMessages
      tags:
      - messages
  /folders/:
    get:
      consumes:
      - application/json
      description: List of outgoing messages
      produces:
      - application/json
      responses:
        "200":
          description: success get list of outgoing messages
          schema:
            $ref: '#/definitions/models.FoldersResponse'
        "400":
          description: failed to get user
          schema: {}
        "401":
          description: failed get session
          schema: {}
      summary: GetFolders
      tags:
      - messages
  /inbox/:
    get:
      consumes:
      - application/json
      description: List of incoming messages
      produces:
      - application/json
      responses:
        "200":
          description: success get list of incoming messages
          schema:
            $ref: '#/definitions/models.InboxResponse'
        "400":
          description: failed to get inbox messages
          schema: {}
        "401":
          description: failed get session
          schema: {}
      summary: GetInboxMessages
      tags:
      - messages
  /logout:
    post:
      consumes:
      - application/json
      description: user log out
      produces:
      - application/json
      responses:
        "200":
          description: success logout
        "401":
          description: failed get session
          schema: {}
      summary: Logout
      tags:
      - users
  /outbox/:
    get:
      consumes:
      - application/json
      description: List of outgoing messages
      produces:
      - application/json
      responses:
        "200":
          description: success get list of outgoing messages
          schema:
            $ref: '#/definitions/models.OutboxResponse'
        "400":
          description: failed to get outbox messages
          schema: {}
        "401":
          description: failed get session
          schema: {}
      summary: GetOutboxMessages
      tags:
      - messages
  /signin:
    post:
      consumes:
      - application/json
      description: user sign in
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.FormLogin'
      produces:
      - application/json
      responses:
        "200":
          description: user created
          schema:
            $ref: '#/definitions/models.SignInResponse'
        "401":
          description: wrong password
          schema: {}
        "403":
          description: invalid form
          schema: {}
        "500":
          description: failed to create session
          schema: {}
      summary: SignIn
      tags:
      - users
  /signup:
    post:
      consumes:
      - application/json
      description: user sign up
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.FormSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: user created
          schema:
            $ref: '#/definitions/models.SignUpResponse'
        "401":
          description: passwords dont match
          schema: {}
        "403":
          description: password too short
          schema: {}
        "409":
          description: user already exists
          schema: {}
        "500":
          description: failed to create session
          schema: {}
      summary: SignUp
      tags:
      - users
swagger: "2.0"
