name: CI

on: [ push ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - name: linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
          make lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - name: build
        run: go build -v ./...
      - name: tests
        run: make test

#  build:
#    name: build
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: actions/setup-go@v3
#        with:
#          go-version: 1.20
#      - uses: actions/checkout@v3
#      - name: build
#        run: make build-binaries