name: CI

on: [ push ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - name: linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -c ./golangci.yml

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - name: tests
        run: make test

#  build:
#    name: build
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: actions/setup-go@v3
#        with:
#          go-version: 1.20
#      - uses: actions/checkout@v3
#      - name: build
#        run: make build-binaries